--AULA 2 DE CARDINALIDADE

--CRIAR TABELA DE CLIENTES
CREATE TABLE TB_CLIENTE (
	ID_CLIENTE INT IDENTITY(1,1),
	NOME VARCHAR(30) NOT NULL,
	PAIS VARCHAR(20) NOT NULL
)
--ALTERAR TABELA PARA CHAVE VIR COM O NOME QUE VOCÊ QUER
ALTER TABLE TB_CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE)
GO

--INSERIR REGISTROS NA TABELA DE CLIENTES
INSERT INTO TB_CLIENTE VALUES 
('WALLACE','PORTUGAL'),
('TULIO','BRASIL')
GO

---CONSULTAR TABELA DE CLIENTES
SELECT * FROM TB_CLIENTE
GO

--CRIAR TABELA DE CONTATOS
CREATE TABLE TB_CONTATO (
	ID_CONTATO INT IDENTITY (1,1),
	TELEFONE VARCHAR(15),
	ID_CLIENTE INT
)
--ALTERAR TABELA PARA CHAVE VIR COM O NOME QUE VOCÊ QUER
ALTER TABLE TB_CONTATO ADD CONSTRAINT PK_CONTATO PRIMARY KEY (ID_CONTATO)
GO
--ALTERAR TABELA PARA CHAVE VIR COM O NOME QUE VOCÊ QUER
ALTER TABLE TB_CONTATO ADD CONSTRAINT FK_CLIENTE_CONTATO FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE (ID_CLIENTE)
GO

--INSERIR REGISTROS NA TABELA DE CONTATOS
INSERT INTO TB_CONTATO VALUES 
('123456',1),
('134562',1),
('134562',2)
GO

--CONSULTAR TABELA DE CONTATOS
SELECT * FROM TB_CONTATO
GO

--CRIAR TABELA DE DOCUMENTOS
CREATE TABLE TB_DOCUMENTOS (
	ID_DOCUMENTO INT IDENTITY (1,1),
	CPF VARCHAR (10),
	ID_CLIENTE INT UNIQUE
)
--ALTERAR TABELA PARA CHAVE VIR COM O NOME QUE VOCÊ QUER
ALTER TABLE TB_DOCUMENTOS ADD CONSTRAINT PK_DOCUMENTO PRIMARY KEY (ID_DOCUMENTO)
--ALTERAR TABELA PARA CHAVE VIR COM O NOME QUE VOCÊ QUER
ALTER TABLE TB_DOCUMENTOS ADD CONSTRAINT FK_CLIENTE_DOCUMENTO FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE (ID_CLIENTE)
GO

--INSERIR REGISTROS NA TABELA DE DOCUMENTOS
INSERT INTO TB_DOCUMENTOS VALUES 
('12345',1),
('54321',2)
GO

--CONSULTAR TABELA DE DOCUMENTOS
SELECT * FROM TB_DOCUMENTOS
GO