--AULA DE CONSTRAINTS

-- NADA SIGNIFICA PERMITE NULL
-- NOT NULL - NÃO PERMITE VAZIOS
-- UNIQUE - NÃO PERMITE VALORES DUPLICADOS
-- PRIMARY KEY - CHAVE PRIMÁRIAS
-- FOREIGN KEY - CHAVE ESTRANGEIRA
-- CHECK - CHECA SE UMA CONDIÇÃO FOI ATENDIDA PARA O DADO


CREATE TABLE TB_TESTE (
	ID_TESTE INT NOT NULL, --NÃO PERMITE NULO
	NOME VARCHAR(50), --NÃO COLOCAR NADA SIGNIFICA QUE PERMITE NULO
	EMAIL VARCHAR(100) UNIQUE, --SOMENTE DADOS ÚNICOS
	SEXO CHAR(1) CHECK (SEXO IN ('M', 'F')) -- CHECA SE UMA CONDIÇÃO FOI ATENDIDA PARA O DADO
)

INSERT INTO TB_TESTE VALUES
(1,'WALLACE','WALLACE@GMAIL.COM','M')

SELECT * FROM TB_TESTE
