--AULA CRIAR TABELA

--CREATE TABLE TABELA (
--	COLUNA TIPO REGRA,
--	COLUNA2 TIPO REGRA,
--)
--GO

CREATE TABLE TB_PRODUTO (
	ID_PRODUTO INT IDENTITY (1,1) ,
	DESCRICAO VARCHAR (50),
	COR VARCHAR (10)
)
GO