--AULA DE DDL (DATA DEFINITION LANGUAGE) 
--DEFINIÇÃO ESTRUTURA

--CRIAR TABELA
--CREATE TABLE NOME_DA_TABELA (
--	COLUNA TIPO, REGRA
--	COLUNA TIPO, REGRA
--)
--GO

CREATE TABLE TB_PROFESSORES (
	ID_PROFESSOR INT,
	NOME VARCHAR(20)
)
GO

--ADICIONAR COLUNA
--ALTER TABLE TABELA ADD NOME_DA_COLUNA TIPO
--GO

ALTER TABLE TB_PROFESSORES ADD PAIS VARCHAR(10)
GO

--REMOVER COLUNA
--ALTER TABLE TABELA DROP COLUMN NOME_DA_COLUNA
--GO

ALTER TABLE TB_PROFESSORES DROP COLUMN PAIS
GO

--APAGAR TABELA
--DROP TABLE TABELA

DROP TABLE TB_PROFESSORES
GO

--CRIAR QUALQUER COISA DE ESTRUTURA --> CREATE
-- ALTERAR QUALQUER COISA DE ESTRUTURA --> ALTER
--APAGAR QUALQUER COISA DE ESTRUTURA --> DROP



