-- EXEMPLOS DE DML (INSERT, UPDATE E DELETE)

--CRIAR TABELA DE VENDAS
CREATE TABLE TB_VENDAS (
	ID_VENDA INT IDENTITY(1,1),
	CLIENTE VARCHAR(20),
	PRECO MONEY,
	QTD_VENDIDA INT
)
GO

--INSERIR REGISTRO NA TABELA DE VENDAS
INSERT INTO TB_VENDAS VALUES 
	('WALLACE',350,2),
	('TULIO',200,5),
	('ADAIL',150,3),
	('JONATHAN',500,1)
GO

--CONSULTAR TABELA DE VENDAS
SELECT * FROM TB_VENDAS
GO

--ATUALIZAR DADOS
--UPDATE TABELA
--SET COLUNA =
--WHERE CONDIÇÃO

UPDATE TB_VENDAS
SET CLIENTE = 'WALLACE CAMARGO'
WHERE CLIENTE = 'WALLACE'
--CLIENTE WALLACE ATUALIZADO PARA WALLACE CAMARGO


--DELETAR DADOS
--DELETE FROM TABELA 
--WHERE COLUNA CONDIÇÃO

DELETE FROM TB_VENDAS
WHERE CLIENTE = 'WALLACE CAMARGO'
--CLIENTE WALACE DELETADO