--AULA DE CONCAT
SELECT 
	[ID_VENDA],
    [DATA_VENDA],
    [ID_CLIENTE],
    [NOME_CLIENTE],
	[LOJA] AS LOJA_ORIGINAL,
    RIGHT([LOJA],1) AS NUM_LOJA,
	LEFT([LOJA],4) AS TIPO,
	CONCAT(LEFT([LOJA],4),' ',RIGHT([LOJA],1)) AS LOJA_CONCAT,
    [VAL_VENDA]
FROM 
	[TB_VENDAS_CLIENTES]





