-- EXTRAIR PRIMEIRO NOME

SELECT 
NOME_COMPLETO,

		-- CONDIÇÃO RETORNA O PRIMEIRO TEXTO ANTES DO PRIMEIRO ESPAÇO
		IIF( 
			SUBSTRING (A.[NOME_COMPLETO],1,CHARINDEX(' ', A.[NOME_COMPLETO])) = ' ',
				A.NOME_COMPLETO,
					SUBSTRING (A.[NOME_COMPLETO],1,CHARINDEX(' ', A.[NOME_COMPLETO]))) AS PRIMEIRO_NOME
			 
  FROM [PRD].[dbo].TB_CLIENTES A;