--AULA DE LAG

SELECT 
	DC.NOME_CLIENTE,
    FV.[DATA],
	LAG(FV.[DATA],1) OVER (PARTITION BY DC.NOME_CLIENTE ORDER BY DC.NOME_CLIENTE, FV.DATA) AS DATA_COMPRA_ANTERIOR,
	DATEDIFF(DAY, LAG(FV.[DATA],1) OVER (PARTITION BY DC.NOME_CLIENTE ORDER BY DC.NOME_CLIENTE), FV.DATA) AS INTERVALO_SEM_COMPRA
FROM 
	[DW].[dbo].[fVendas] FV
	INNER JOIN dCliente DC
		ON FV.ID_CLIENTE = DC.ID_CLIENTE
GROUP BY 
	DC.NOME_CLIENTE,
    FV.[DATA]