--AULA DE TABELA TEMPORÁRIA

CREATE TABLE TB_PROFESSORES (
	ID_PROFESSOR INT IDENTITY (1,1),
	NOME VARCHAR(20),
	SALARIO MONEY
)
GO
ALTER TABLE TB_PROFESSORES ADD CONSTRAINT PK_PROFESSOR PRIMARY KEY (ID_PROFESSOR)
GO

INSERT INTO TB_PROFESSORES VALUES ('WALLACE',6000)
INSERT INTO TB_PROFESSORES VALUES ('TULIO',7000)
GO

SELECT * FROM TB_PROFESSORES
GO

--APAGA A TABELA TEMPORÁRIA, CASO EXISTA
DROP TABLE IF EXISTS #TOTAL_SALARIO
GO

--CRIAÇÃO DA TABELA TEMPORÁRIA 
SELECT 
	SUM(SALARIO) AS TOTAL
INTO 
	#TOTAL_SALARIO
FROM
	TB_PROFESSORES

SELECT * FROM #TOTAL_SALARIO
GO

SELECT 
	NOME,
	SALARIO,
	(SELECT MIN(TOTAL) FROM #TOTAL_SALARIO)	AS TOTAL,
	SALARIO / (SELECT MAX(TOTAL) FROM #TOTAL_SALARIO)*100 AS PERCENTUAL
FROM 
	TB_PROFESSORES






