-- EXEMPLO DE DROP

--CRIAR TABELA
CREATE TABLE TB_PROFESSORES (
	ID INT IDENTITY (1,1),
	NOME VARCHAR(20) NOT NULL,
	PAIS VARCHAR(20) NOT NULL
)
GO

--POPULAR TABELA
INSERT INTO TB_PROFESSORES VALUES ('WALLACE','PORTUGAL')
INSERT INTO TB_PROFESSORES VALUES ('TULIO','BRASIL')
GO

--CONSULTAR TABELA
SELECT * FROM TB_PROFESSORES
GO

--APAGAR TABELA
DROP TABLE TB_PROFESSORES
GO