-- LIMPAR TODAS AS LINHAS DA TABELA TRUNCATE

--CRIAR TABELA
CREATE TABLE TB_PROFESSORES (
	ID INT IDENTITY (1,1) PRIMARY KEY,
	NOME VARCHAR(20) NOT NULL,
	PAIS VARCHAR(20) NOT NULL
)

--INSERIR DADOS NA TABELA
INSERT INTO TB_PROFESSORES VALUES ('WALLACE','PORTUGAL')
INSERT INTO TB_PROFESSORES VALUES ('TULIO','BRASIL')

--CONSULTA NA TABELA
SELECT * FROM TB_PROFESSORES

--LIMPAR REGISTROS NA TABELA
TRUNCATE TABLE TB_PROFESSORES