--CRIAR TABELA

--CREATE TABLE TABELA (
--	NOME_COLUNA TIPO_DE_DADO REGRA_DA_COLUNA,
--	NOME_COLUNA TIPO_DE_DADO REGRA_DA_COLUNA,
--)
--GO

CREATE TABLE TB_PRODUTO (
	ID_PRODUTO INT IDENTITY (1,1) ,
	DESCRICAO VARCHAR (50) NOT NULL,
	COR VARCHAR (10) NULL
)
GO