CREATE DATABASE ANALISE_DADOS
GO

USE ANALISE_DADOS
GO

CREATE TABLE TB_CLIENTE (
	ID_CLIENTE INT IDENTITY(1,1),
	NOME VARCHAR(30) NOT NULL,
	PAIS VARCHAR(20) NOT NULL
)
--ALTERAR TABELA PARA CHAVE VIR COM O NOME QUE VOCÊ QUER
ALTER TABLE TB_CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE)
GO


CREATE TABLE TB_TELEFONE (
	ID_TELEFONE INT IDENTITY (1,1),
	TELEFONE VARCHAR (15),
	ID_CLIENTE INT NOT NULL
)
--ALTERAR TABELA PARA CHAVE VIR COM O NOME QUE VOCÊ QUER
ALTER TABLE TB_TELEFONE ADD CONSTRAINT PK_TELEFONE PRIMARY KEY (ID_TELEFONE)
GO
--ALTERAR TABELA PARA CHAVE VIR COM O NOME QUE VOCÊ QUER
ALTER TABLE TB_TELEFONE ADD CONSTRAINT FK_CLIENTE_TELEFONE FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE (ID_CLIENTE)
GO


CREATE TABLE TB_DOCUMENTOS (
	ID_DOCUMENTO INT IDENTITY (1,1),
	CPF VARCHAR (10) NOT NULL,
	ID_CLIENTE INT NOT NULL
)
--ALTERAR TABELA PARA CHAVE VIR COM O NOME QUE VOCÊ QUER
ALTER TABLE TB_DOCUMENTOS ADD CONSTRAINT PK_DOCUMENTO PRIMARY KEY (ID_DOCUMENTO)
--ALTERAR TABELA PARA CHAVE VIR COM O NOME QUE VOCÊ QUER
ALTER TABLE TB_DOCUMENTOS ADD CONSTRAINT FK_CLIENTE_DOCUMENTO FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE (ID_CLIENTE)
--ALTERAR TABELA PARA CHAVE VIR COM O NOME QUE VOCÊ QUER
ALTER TABLE TB_DOCUMENTOS ADD CONSTRAINT UNIQ_CLIENTE UNIQUE (ID_CLIENTE) 
GO



CREATE TABLE TB_EMAIL (
	ID_EMAIL INT IDENTITY (1,1),
	EMAIL VARCHAR (100),
	ID_CLIENTE INT NOT NULL
)
--ALTERAR TABELA PARA CHAVE VIR COM O NOME QUE VOCÊ QUER
ALTER TABLE TB_EMAIL ADD CONSTRAINT PK_EMAIL PRIMARY KEY (ID_EMAIL)
--ALTERAR TABELA PARA CHAVE VIR COM O NOME QUE VOCÊ QUER
ALTER TABLE TB_EMAIL ADD CONSTRAINT FK_CLIENTE_EMAIL FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE (ID_CLIENTE)
--ALTERAR TABELA PARA CHAVE VIR COM O NOME QUE VOCÊ QUER
ALTER TABLE TB_EMAIL ADD CONSTRAINT UNIQ_EMAIL_CLIENTE UNIQUE (ID_CLIENTE) 
GO


--INSERIR REGISTROS NA TABELA DE CLIENTES
INSERT INTO TB_CLIENTE VALUES 
('WALLACE','PORTUGAL'),
('TULIO','BRASIL'),
('MIDIAN','BRASIL')
GO


--INSERIR REGISTROS NA TABELA DE CONTATOS
INSERT INTO TB_TELEFONE VALUES 
(NULL,2),
('123456',1),
('134562',1),
('12345',3),
('54321',3)

GO

--INSERIR REGISTROS NA TABELA DE DOCUMENTOS
INSERT INTO TB_DOCUMENTOS VALUES 
('12345',1),
('54321',2),
('32155',3)
GO

--INSERIR REGISTROS NA TABELA DE EMAIL
INSERT INTO TB_EMAIL VALUES 
('WALLACE@GMAIL',1),
('TULIO@GMAIL',2),
(NULL,3)
GO