--EXEMPLOS DE DDL (DATA DEFINITION LANGUAGE) 
--DEFINIÇÃO ESTRUTURA

--CRIAR TABELA
--CREATE TABLE COLUNAS,TIPOS DE DADOS E CONSTRAINTS
CREATE TABLE TB_PROFESSORES (
	ID_PROFESSOR INT,
	NOME VARCHAR(20)
)
GO

--ADICIONAR COLUNA
--ALTER TABLE TABELA ADD NOME_DA_COLUNA TIPO
ALTER TABLE TB_PROFESSORES ADD PAIS VARCHAR(10)
GO

--REMOVER COLUNA
--ALTER TABLE TABELA DROP COLUMN NOME_DA_COLUNA
ALTER TABLE TB_PROFESSORES DROP COLUMN PAIS
GO

--APAGAR TABELA
--DROP TABLE TABELA
DROP TABLE TB_PROFESSORES
GO

--CRIAR QUALQUER OBJETO --> CREATE
--ALTERAR ESTRUTURA DE QUALQUER OBJETO --> ALTER
--APAGAR QUALQUER OBJETO --> DROP