--AULA DE FUNCTION DE TABELA

--CRIAR TABELA
CREATE TABLE TB_ESTOQUE (
	ID INT IDENTITY(1,1),
	PRODUTO VARCHAR(20),
	CUSTO_UNIT MONEY,
	QTD INT
)
GO

--INSERIR REGISTRO NA TABELA 
INSERT INTO TB_ESTOQUE VALUES 
	('AUTOMOVEL',23470,5),
	('HELICOPTERO',500000,1),
	('BARCO',20000,5),
	('MOTOCICLETA',10000,8)
GO

--CONSULTA NA TABELA
SELECT * FROM TB_ESTOQUE

--CONSTRUÇÃO DA FUNÇÃO ESCALAR
CREATE FUNCTION TB_PRODUTOS_VIP (@CUSTO MONEY)
RETURNS TABLE
AS RETURN
SELECT
	PRODUTO,
	CUSTO_UNIT
FROM
	TB_ESTOQUE
WHERE
	CUSTO_UNIT >= @CUSTO
GO

--CHAMADA DA FUNÇÃO
SELECT * FROM DBO.TB_PRODUTOS_VIP (20000)	