--CONCATENAR COLUNAS

--O SINAL DE MAIS "+" SERVE PARA CONCATENAR CAMPOS
--SE TENTAR CONCATENAR COLUNAS NUMÉRICAS IRÁ SOMAR

CREATE TABLE TB_CLIENTE (
	NOME VARCHAR(50),
	SOBRENOME VARCHAR(50)
)

INSERT INTO TB_CLIENTE VALUES 
('WALLACE','CAMARGO'),
('SHALOM','ANDRE'),
('ITALO','MESQUITA'),
('LUIZ','LIMA')


SELECT * FROM TB_CLIENTE;

SELECT
NOME +' '+ SOBRENOME AS NOME_COMPLETO

FROM TB_CLIENTE


--CONCATENAR AINDA QUE NUMÉRICAS
SELECT
CONCAT(NOME,' ', SOBRENOME) AS NOME_COMPLETO
FROM TB_CLIENTE


