--EXEMPLO DE CTE

CREATE TABLE TB_PROFESSORES (
	ID_PROFESSOR INT IDENTITY (1,1),
	NOME VARCHAR(20),
	SALARIO MONEY
)
GO
ALTER TABLE TB_PROFESSORES ADD CONSTRAINT PK_PROFESSOR PRIMARY KEY (ID_PROFESSOR)
GO

INSERT INTO TB_PROFESSORES VALUES ('WALLACE',6000)
INSERT INTO TB_PROFESSORES VALUES ('TULIO',7000)
GO

SELECT * FROM TB_PROFESSORES
GO


--CRIAÇÃO DA CTE
WITH TOTAL_SALARIOS
AS 
(
SELECT 
	SUM(SALARIO) AS TOTAL
FROM
	TB_PROFESSORES
)
SELECT 
	NOME,
	SALARIO,
	(SELECT MAX(TOTAL) FROM TOTAL_SALARIOS)	AS TOTAL,
	SALARIO / (SELECT MAX(TOTAL) FROM TOTAL_SALARIOS)*100 AS PERCENTUAL
FROM 
	TB_PROFESSORES







