--EXEMPLO DE DATEDIFF 

--CRIAR TABELA DE CLIENTES
CREATE TABLE TB_CLIENTES (
	NOME VARCHAR(50),
	DATA_NASCIMENTO DATE
)
GO

--INSERIR UM CLIENTE
INSERT INTO TB_CLIENTES VALUES
('WALLACE','1988-11-07')
GO

--COMO CALCULAR A IDADE?
SELECT
	NOME,
	DATA_NASCIMENTO,
	--FUNÇÃO ABAIXO CRIA A DIFERENÇA ENTRE DATAS
	DATEDIFF(YEAR,DATA_NASCIMENTO,GETDATE()) AS IDADE
FROM
	TB_CLIENTES
