-- EXTRAIR PRIMEIRO NOME

CREATE TABLE TB_NOMES (
	NOME_COMPLETO VARCHAR(50)
)
GO

INSERT INTO TB_NOMES VALUES
('WALLACE CAMARGO'),
('SHALOM ANDRE'),
('ITALO MESQUITA'),
('LUIZ LIMA')


SELECT 
NOME_COMPLETO,

		-- CONDIÇÃO RETORNA O PRIMEIRO TEXTO ANTES DO PRIMEIRO ESPAÇO
		IIF( 
			SUBSTRING (A.[NOME_COMPLETO],1,CHARINDEX(' ', A.[NOME_COMPLETO])) = ' ',
				A.NOME_COMPLETO,
					SUBSTRING (A.[NOME_COMPLETO],1,CHARINDEX(' ', A.[NOME_COMPLETO]))) AS PRIMEIRO_NOME
			 
  FROM TB_NOMES A;