--EXEMPLOS DE JOIN


--CRIAR TABELA DE CLIENTES
CREATE TABLE TB_CLIENTES (
ID_CLIENTE INT IDENTITY (1,1) PRIMARY KEY,
NOME_CLIENTE VARCHAR (20),
MORADA_CLIENTE VARCHAR (50),
SEXO_CLIENTE CHAR(1)
)

--INSERIR REGISTROS NA TABELA DE CLIENTES
INSERT INTO TB_CLIENTES VALUES ('WALLACE', 'RUA DE PORTUGAL','M')
INSERT INTO TB_CLIENTES VALUES ('SIDNEY', 'RUA DE AVEIRO','M')
INSERT INTO TB_CLIENTES VALUES ('KAMILLA', 'RUA DE LEIRIA','F')
INSERT INTO TB_CLIENTES VALUES ('KAROL', 'RUA DE REALENGO','F')
INSERT INTO TB_CLIENTES VALUES ('ARAO', 'RUA DE COLEGIO','M')
INSERT INTO TB_CLIENTES VALUES ('ROGERIO', 'RUA DE CORDOVIL','M')
INSERT INTO TB_CLIENTES VALUES ('GISELLE', 'RUA DE OLIVEIRA','F')
INSERT INTO TB_CLIENTES VALUES ('DULCE', 'RUA DE CANECAS','F')

--CONSULTA PARA EXIBIR TODA A TABELA DE CLIENTES
SELECT * FROM TB_CLIENTES

--CRIAR TABELA DE NASCIMENTO DOS CLIENTES
CREATE TABLE TB_NASCIMENTO_CLIENTES (
ID_CLIENTE INT IDENTITY (1,1) PRIMARY KEY,
DATA_NASCIMENTO DATE
)

--INSERIR CLIENTES COM DATA DE NASCIMENTO
INSERT INTO TB_NASCIMENTO_CLIENTES VALUES 
('07/11/1988'),
('12/10/1999'),
('07/11/1989'),
('07/10/1990'),
('06/10/2000'),
('05/11/1988'),
('06/11/1988')


--CONSULTA PARA EXIBIR TODA A TABELA NACIMENTO CLIENTES
SELECT * FROM TB_NASCIMENTO_CLIENTES

--INNER JOIN (EXIBE APENAS DADOS QUE CONTÉM A MESMA CHAVE EM AMBAS AS TABELAS)
SELECT 
	TC.[ID_CLIENTE],
	TC.[NOME_CLIENTE],
	TC.[MORADA_CLIENTE],
	TC.[SEXO_CLIENTE],
	TNC.DATA_NASCIMENTO
FROM 
	[TB_CLIENTES] TC
	INNER JOIN TB_NASCIMENTO_CLIENTES TNC ON TC.ID_CLIENTE = TNC.ID_CLIENTE 

--LEFT JOIN (OS DADOS QUE CONTÉM A CHAVE SÓ NA TABELA DO FROM (ESQUERDA), SERÃO EXIBIDOS COMO NULO NA CONSULTA)

SELECT 
	TC.[ID_CLIENTE],
	TC.[NOME_CLIENTE],
	TC.[MORADA_CLIENTE],
	TC.[SEXO_CLIENTE],
	TNC.DATA_NASCIMENTO
FROM 
	[TB_CLIENTES] TC
	LEFT JOIN TB_NASCIMENTO_CLIENTES TNC ON TC.ID_CLIENTE = TNC.ID_CLIENTE 