--LEFT JOIN

--Quando usar o Left Join?
--R: Quando quiser manter tudo que está na esquerda e o que vier da direita virá como null 

CREATE TABLE TB_ALUNOS(
	ID_CLIENTE INT,
	NOME VARCHAR(50)
)
GO

INSERT INTO TB_ALUNOS VALUES
(1,'WALLACE'),
(2,'TULIO'),
(3,'MIDIAN'),
(4,'ADAIL'),
(5,'ANDERSON'),
(6,'BRUNO'),
(7,'DANILO'),
(8,'EDUARDO')
GO

CREATE TABLE TB_EMAIL(
	ID_CLIENTE INT,
	EMAIL VARCHAR(50)
)
GO

INSERT INTO TB_EMAIL VALUES
(1,'WALLACE@GMAIL'),
(2,'TULIO@GMAIL')
GO

--JUNTAR TABELAS E MANTER CLIENTES SEM E-MAIL
SELECT 
	TA.ID_CLIENTE,
	TA.NOME,
	TE.EMAIL
FROM
	TB_ALUNOS TA
	LEFT JOIN TB_EMAIL TE ON TA.ID_CLIENTE = TE.ID_CLIENTE
