--EXEMPLOS DE CONSULTAS, DICAS E SINTAXE

--CRIAR TABELA DE EXEMPLOS
CREATE TABLE TB_PRODUTO (
	ID_PRODUTO INT IDENTITY (1,1),
	PRODUTO VARCHAR(30),
	CATEGORIA VARCHAR (20),
	COR VARCHAR (10),
	PREÇO MONEY
)
GO

--INSERIR DADOS
INSERT INTO TB_PRODUTO VALUES
('IPHONE','TELEFONE','PRETO',12000),
('ANDROID','TELEFONE','PRETO',5000),
('TABLET','ELETRÔNICOS','BRANCO',2500),
('IPHONE','TELEFONE','BRANCO',12000),
('ANDROID','TELEFONE','BRANCO',5000),
('IPHONE','TELEFONE','ROSA',12000)


--CONSULTAR DADOS É LER OS DADOS 

/*
SELECT 
	ID_PRODUTO,
	PRODUTO,
	CATEGORIA,
	COR,
	PREÇO
FROM  
	TB_PRODUTO
GO
*/

--ESTRUTURA 
--SELECT
--	COLUNAS
--FROM
--	TABELA

--* = TODAS
--EVITE * UTILIZE APENAS EM TESTE 
--SELECT * FROM TABELA

--DELIMITADOR 
--GO OU ; 
--O SQL SERVER VAI FAZER O QUE É MAIS RÁPIDO PRIMEIRO E TUDO EM PARALELO

--CRIAR COMENTÁRIO 
--
/* BLOCO */

--================================================
--ESTRUTURA LÓGICA DE UMA CONSULTA
--SELECT 
--	COLUNA1,
--	COLUNA2
--FROM
--	TABELA

--WHERE 
--	COLUNA CONDIÇÃO
-- OPERADOR LÓGICO PARA MAIS DE UMA CONDIÇÃO

--GROUP BY 
--	COLUNA AGRUPADA

--HAVING 
--	FILTRO DA COLUNA AGRUPADA

--ORDER BY
--	ORDENAR CONSULTA POR CRITÉRIO
--=============================================
--FIM DA LÓGICA


-- GROUP BY É OBRIGATÓRIO SEMPRE QUE USAR AGREGAÇÃO
--SUM SOMA
--COUNT CONTAGEM
--AVG MÉDIA
--MAX MÁXIMO
--MIN MÍNIMO

--TODO TEXTO É ENTRE ASPAS SIMPLES
-- NÚMERO NÃO USA ASPAS 



--TROCAR O NOME DA COLUNA NA CONSULTA
--SELECT
--	COLUNA1 NOME_TROCADO
--	COLUNA2 AS NOME_TROCA 

--FROM
--	TABELA

--AS COLUNAS VIRÃO NA ORDEM QUE VOCÊ DETERMINAR
	

--CONSULTAR DUAS TABELAS AO MESMO TEMPO 



--SALVAR UMA QUERY


--NÃO DECORE NADA, ENTENDA A LÓGICA


SELECT * FROM TB_PRODUTO
GO

SELECT
	SUM(PREÇO) AS PRECO,
	PRODUTO
FROM
	TB_PRODUTO
WHERE 
	PRODUTO = 'IPHONE'
GROUP BY
	PRODUTO 
