--EXEMPLO DE STUFF 

CREATE TABLE [dbo].[TB_EMAIL_RELATORIOS](
	[SK_GERENTE] [int] IDENTITY(1,1) NOT NULL,
	[NUM_LOJA] [int] NULL,
	[EMAIL] [varchar](100) NULL,
) 
GO

INSERT INTO TB_EMAIL_RELATORIOS VALUES
(1,'PAULO@GMAIL'),
(1,'GUSTAVO@GMAIL'),
(1,'HENRIQUE@GMAIL'),
(2,'PATRICIA@GMAIL'),	
(2,'DANIEL@GMAIL'),	
(2,'PEDRO@GMAIL'),	
(2,'ALLAN@GMAIL'),	
(3,'GABRIEL@GMAIL'),
(3,'JAQUELINE@GMAIL'),
(4,'RAUL@GMAIL'),
(5,'MONIQUE@GMAIL')
GO

SELECT * FROM TB_EMAIL_RELATORIOS
GO

SELECT
	NUM_LOJA, --COLUNA QUE EU QUERO MANTER NA LINHA
	STUFF((SELECT DISTINCT ';' + EMAIL  FROM TB_EMAIL_RELATORIOS T1 --LINHA QUE QUERO NA COLUNA 
	   WHERE T1.NUM_LOJA = T2.NUM_LOJA --COLUNA QUE EU QUERO MANTER NA LINHA
	   FOR XML PATH('')),1,1,'') AS EMAIL --LINHA QUE QUERO NA COLUNA
FROM 
	TB_EMAIL_RELATORIOS T2
GROUP BY 
	NUM_LOJA --COLUNA QUE EU QUERO MANTER NA LINHA