--EXEMPLO DE TABELA TEMPORARIA

IF OBJECT_ID ('TEMPDB..#PALAVRAS_TRADUZIDAS ') IS NOT NULL DROP TABLE #PALAVRAS_TRADUZIDAS;

CREATE TABLE #PALAVRAS_TRADUZIDAS (
	ID INT,
	PALAVRA VARCHAR (15),
	LINGUAGEM VARCHAR (10)
);

INSERT INTO #PALAVRAS_TRADUZIDAS VALUES (1,'CASA', 'PORTUGUES')
INSERT INTO #PALAVRAS_TRADUZIDAS VALUES (2,'CIDADE', 'PORTUGUES')
INSERT INTO #PALAVRAS_TRADUZIDAS VALUES (3,'CACHORRO', 'PORTUGUES')
INSERT INTO #PALAVRAS_TRADUZIDAS VALUES (4,'AGUA', 'PORTUGUES')
INSERT INTO #PALAVRAS_TRADUZIDAS VALUES (5,'CARRO', 'PORTUGUES')

--CONSULTA NA TABELA TEMPORARIA
SELECT * FROM #PALAVRAS_TRADUZIDAS    
    
    
 --CASO 2
 --INSERINDO DADOS EXISTENTES EM UMA TABELA TEMPORÁRIA

IF OBJECT_ID ('TEMPDB..#TABELA_TEMPORARIA') IS NOT NULL DROP TABLE #TABELA_TEMPORARIA;

SELECT 
	*
INTO
	#TABELA_TEMPORARIA	
FROM 
	[TB_CLIENTES]

SELECT * FROM #TABELA_TEMPORARIA