--EXEMPLOS DE UNION

--UNION --> REMOVE OS DUPLICADOS NA JUNÇÃO
--UNION ALL --> JUNTA AS DUAS TABELAS INTEIRAS

DROP TABLE IF EXISTS TB_PRODUTOS_INATIVOS 
GO
CREATE TABLE TB_PRODUTOS_INATIVOS(
	ID_PRODUTO INT IDENTITY (1,1),
	PRODUTO VARCHAR(20),
	CATEGORIA VARCHAR(20),
	COR VARCHAR(10),
	PREÇO MONEY 
)
GO

INSERT INTO TB_PRODUTOS_INATIVOS VALUES
('VIDEOCASSETE','ELETRÔNICOS','PRETO',100),
('PEN DRIVE','PERIFÉRICOS','VERMELHO',50),
('MP3 PLAYER','PERIFÉRICOS','AZUL',200),
('MP3 PLAYER','PERIFÉRICOS','BRANCO',200)
GO

SELECT * FROM TB_PRODUTOS_INATIVOS
SELECT * FROM TB_PRODUTO

--UNION
SELECT PRODUTO,PREÇO,'ATIVO' AS STATUS FROM TB_PRODUTO
UNION
SELECT  PRODUTO,PREÇO,'INATIVOS' AS STATUS FROM TB_PRODUTOS_INATIVOS

--UNION ALL
SELECT PRODUTO,PREÇO,'ATIVO' AS STATUS FROM TB_PRODUTO
UNION ALL
SELECT  PRODUTO,PREÇO,'INATIVOS' AS STATUS FROM TB_PRODUTOS_INATIVOS