--INSERIR ARQUIVO BINÁRIO

-- CRIAR UMA TABELA QUE RECEBERÁ DADO DO TIPO BINÁRIO
CREATE TABLE DADOS_BINARIOS (
  ID INT IDENTITY (1,1) PRIMARY KEY,
  ARQUIVO VARBINARY(MAX)
)


--INSERIR ARQUIVO NA TABELA
INSERT INTO DADOS_BINARIOS (ARQUIVO)  
SELECT
	BULKCOLUMN FROM OPENROWSET(BULK 'caminho_do_arquivo.PNG' ,SINGLE_BLOB) AS ARQUIVO

SELECT * FROM DADOS_BINARIOS