--FUNCTION QUE TRATA DIVISAO POR ZERO

--CRIAR TABELA
CREATE TABLE TB_VENDAS_ANUAL (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	PRODUTO VARCHAR(20),
	ANO_ANTERIOR MONEY,
	ANO_ATUAL MONEY
)
GO

--INSERIR DADOS
INSERT INTO TB_VENDAS_ANUAL VALUES ('TABLET',300,350)
INSERT INTO TB_VENDAS_ANUAL VALUES ('ANDROID',400,300)
INSERT INTO TB_VENDAS_ANUAL VALUES ('MACBOOK',550,1100)
INSERT INTO TB_VENDAS_ANUAL VALUES ('IPHONE',0,100)
GO

--DIVISAO COM ERRO
SELECT  
	PRODUTO,
	ANO_ANTERIOR,
	ANO_ATUAL,
	((ANO_ATUAL - ANO_ANTERIOR) / ANO_ANTERIOR)*100 AS VARIACAO
FROM 
	TB_VENDAS_ANUAL
GO

--CRIAÇÃO DA FUNÇÃO
CREATE FUNCTION dbo.TRATA_DIVISAO_POR_ZERO (
	@PERANT MONEY,
	@PERATUAL MONEY
)
RETURNS
	MONEY
BEGIN
	RETURN
		CASE
			WHEN @PERATUAL = 0 THEN 0
			WHEN @PERANT = 0 THEN 0
		ELSE
			((@PERATUAL - @PERANT) / @PERANT)*100
		END

END
GO

--CONSULTA COM A FUNÇÃO
SELECT  
	PRODUTO,
	ANO_ANTERIOR,
	ANO_ATUAL,
	[dbo].TRATA_DIVISAO_POR_ZERO (ANO_ANTERIOR,ANO_ATUAL) AS VARIACAO
FROM 
	TB_VENDAS_ANUAL
GO
