DROP DATABASE IF EXISTS ADM
GO
CREATE DATABASE ADM 
GO
USE ADM
GO

DROP TABLE IF EXISTS TB_REGISTRO
GO
CREATE TABLE TB_REGISTRO(
	ID_REGISTRO INT IDENTITY (1,1),
	DATA_REGISTRO DATETIME,
	USUARIO VARCHAR(50)
)
GO

BEGIN TRAN T1
GO
INSERT INTO TB_REGISTRO VALUES 
(GETDATE(),System_User)
GO

--CONSULTAR TRANSAÇÕES ABERTAS
SELECT @@TRANCOUNT

--ABRA UMA NOVA QUERY E REALIZE UM CONSULTA NA TABELA
SELECT * FROM TB_REGISTRO

--CONSULTAR DETALHES DAS TRANSAÇÕES
exec sp_who2

--ABRA UMA NOVA QUERY E EXECUTE O COMANDO PARA MATAR SESSÃO 
KILL 54 --BASTA ALTERAR O NUMERO

--DESFAZER TRANSAÇÃO
ROLLBACK TRAN T1

--CONFIRMAR TRANSAÇÃO
COMMIT TRAN T1

--LIMPAR TABELA
TRUNCATE TABLE TB_REGISTRO

