--AULA DE INSERIR UM CSV NO BANCO DE DADOS

--CRIAR TABELA
CREATE TABLE TB_NOME_PAIS(
	NOME VARCHAR(20),
	PAIS VARCHAR(20)
)
GO

BULK INSERT
TB_NOME_PAIS FROM 'Caminho do CSV.csv'
WITH
(
	FIRSTROW = 2,
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n'
)